version: '3.8'
services:

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        depends_on: 
            - influxdb
        volumes: 
            - grafana_volume:/var/lib/grafana
        restart: always
    
    influxdb:
        image: influxdb:1.8.3
        container_name: influxdb
        ports:
            - 8086:8086
        volumes: 
            - influxdb_volume:/var/lib/influxdb
        restart: always
        
    telegraf:
        image: telegraf:latest
        container_name: telegraf
        ports:
            - 161:161/udp
        links:
            - influxdb
        volumes: 
            - telegraf_volume:/etc/telegraf
            # MIBs need to be imported into this volume
            - mib_volume:/usr/share/snmp
        restart: always

networks: 

    grafana_network:
        name: grafana_network
        driver: bridge

volumes: 

    grafana_volume:
        name: grafana_volume
    
    telegraf_volume:
        name: telegraf_volume

    influxdb_volume:
        name: influxdb_volume

    mib_volume:
        name: mib_volume